format = """
$directory\
$git_branch\
$git_status\
$golang\
$rust\
$nodejs\
$python\
$lua\
$terraform\
$cmd_duration\
$line_break\
$character"""

[directory]
truncation_length = 4
truncate_to_repo = true

[git_branch]
symbol = " "

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
staged = "[+${count}](green)"
modified = "[~${count}](yellow)"
untracked = "[?${count}](blue)"
deleted = "[-${count}](red)"

[golang]
symbol = " "

[rust]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[lua]
symbol = " "

[terraform]
format = "[$symbol$workspace]($style) "

[cmd_duration]
min_time = 2_000
format = "[$duration](yellow) "

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
